### ISSUE TITLE
'BEM' and 'CSS Modules'

### ISSUE THREAD

**Issue by Xuhv** [Xuhv/something#1]
# 'BEM', 'Preprocessor' and 'CSS Modules'

## BEM

`BEM` is short of "Block Element Modifier", a methodology to create reusable components and code sharing in front-end development.

With `BEM`, the css like this:

```css
.list {
    display: flex;
    flex-direction: column;
    background-color: rgb(30, 41, 51);
}
.list-item {
    height: 1.5em;
    padding: .2em;
    text-indent: 1.5em;
}
.list-item_active {
    /* append the class to the classList to avoid repeating css code */
    background-color: rgb(97, 118, 138);
}
```
And we can also use an independent class

```css
.list-item.active {
    background-color: rgb(97, 118, 138);
}
```
With `BEM`, the css is written in Modular, but sometimes we have to write some complex html in a single file cause the too long class names which we don't want. To avoid that,  I may write css like

```css
.list-item {
    /* this is the container element of .content */
}
.content {
    /* ... */
}
.content-part1 {
    /* ... */
}
.content-part2 {
    /* ... */
}
```
We reduce the length of the class names, howerve, the classes will afect the elements with same className outside the list. In other words, we break it's modularity.

Fortunately, we have `preprocessor`. With `Sass` or `Less`, we can write nested rules. We code less, and compiler complete the rest.

```scss
.list-item {
    .content {
        /* ... */
    }
}
```
I prefer anothor method <sup id="bem-scss">[1]</sup>

```scss
.list-item_active {
    &-content {
        /* className is still lengthy, but so what ? */
    }
}
```
## CSS Modules

The similar effect can be achieved with `CSS Modules`.

```scss
// Article.module.scss
.Root {
    .Title{
        font-size: 24px;
        color: purple;
    }
    .Content {
        font-size: 14px;
    }
}
```
```ts react
import styles from "Article.module.scss";

function Article() {
    return (
        <div className={styles.Root}>
            <div className={styles.Title}>Title</div>
            <div className={styles.Content}>
                床前明月光，疑是地上霜；
                举头望明月，低头思故乡。
            </div>
        </div>
    );
}

```

I believe it's best benefit is fully semantic so that we can code less and having better editor support than [1](#bem-scss)
